import Vue from 'vue'
import Router from 'vue-router'
import {
	Login,
	Portal,
    cardPassword,
    Rechargerecord,
    transferCard,
    producePass,
    allsChange,
    airRecharge,
    cardRecharge,
    phoneShezhi,
    cardAdministrator,
    changeOnepage,
    addAdmian,
    partnerMg,
    storeList,
    storeType,
    Businessheadline,
    addHeadline,
    changeHeader,
    Merchantcash,
    Businessaudit,
    userFeedback,
    commonProblem,
    Tariffdescription,
    costSay,
    addcostSay,
    Novice,
    addNovice,
    changeCost,
    changeCommonpro,
    markstoreList,
    Portal2,
    changeNovice,
    phoneSettings,
    shopSettings,
    onlineSettings,
    addCommonpro,
    phoneImage,
    addshopSetting,
    onlineSetting,
    addShoptype,
    changeStoretype,
    addPartner,
    changeMg,
    addStore,
    changeStore,
    changeDiscon,
    purchaseHeader,
    addShoptab,
    userAdministrator,
    changeUser,
    cardChongzhi,
    purchaseOrder,
    returnedOrders,
    changePassword,
    getCash,
    electricitySupplier,
    updataWord,
    keywordJudgement,
    activityContent,
    activityBack,
    addActive,
    setingChuangke,
    qrcodeList,
    getQcode,
    getMessage,
    addActiveback,
    deleteQrcode,
    addDongtai,
    addAdm,
    changheader,
    chongfuOrder,
    leadingIn
} from '@/pages'

Vue.use(Router)

var router = new Router({
	routes: [
		{
			path: '/',
			redirect: '/login'
		},
		{
			path: '/login',
			component: Login
		},
        // {
        //     path:'/getQcode',
        //     component:getQcode
        // },
		{
			path:'/portal2',
			component:Portal2,
			children:[
				{
					path:'/',
					redirect:'/markstoreList'
				},
				{
					path:'/markstoreList',
                    component:markstoreList
				}
			]
		},
		{
			path: '/portal',
			component: Portal,
			children: [
				{
					path:'/',
					redirect:'/cardPassword'
				},
				{
					path:'/cardPassword',
					component:cardPassword
				},
				{
					path:'/transferCard',
					component:transferCard
				},
				{
					path:'/producePass',
					component:producePass
				},
				{
					path:'/allsChange',
					component:allsChange
				},
				{
					path:'/airRecharge',
					component:airRecharge
				},
				{
					path:'/cardRecharge',
					component:cardRecharge
				},
				{
					path:'/phoneShezhi',
					component:phoneShezhi
				},
				{
					path:'/Rechargerecord',
					component:Rechargerecord
				},
				{
					path:'/cardAdministrator',
					component:cardAdministrator
				},
				{
					path:'/addAdmian',
					component:addAdmian
				},
				{
					path:'/changeOnepage',
					component:changeOnepage
				},
				{
					path:'/partnerMg',
					component:partnerMg
				},
				{
					path:'/storeList',
					component:storeList
				},
				{
					path:'/storeType',
					component:storeType
				},
				{
					path:'/Businessheadline',
					component:Businessheadline
				},
				{
					path:'/addHeadline',
					component:addHeadline
				},
				{
					path:'/changeHeader',
					component:changeHeader
				},
				{
					path:'/Merchantcash',
					component:Merchantcash
				},
				{
					path:'/Businessaudit',
					component:Businessaudit
				},
				{
					path:'/userFeedback',
					component:userFeedback
				},
				{
					path:'/commonProblem',
					component:commonProblem
				},
				{
					path:'/Tariffdescription',
					component:Tariffdescription
				},
				{
					path:'/costSay',
					component:costSay
				},
				{
					path:'/addcostSay',
					component:addcostSay
				},
				{
					path:'/Novice',
					component:Novice
				},
				{
					path:'/addNovice',
					component:addNovice
				},
				{
					path:'/changeCost',
					component:changeCost
				},
				{
					path:'/changeCommonpro',
					component:changeCommonpro
                },
				{
					path:'/changeNovice',
					component:changeNovice
				},
				{
					path:'/phoneSettings',
					component:phoneSettings
                },
				{
					path:'/shopSettings',
					component:shopSettings
				},
				{
					path:'/onlineSettings',
					component:onlineSettings
				},
				{
					path:'/addCommonpro',
					component:addCommonpro
				},
				{
					path:'/phoneImage',
					component:phoneImage
				},
				{
					path:'/addshopSetting',
					component:addshopSetting
				},
				{
					path:'/onlineSetting',
					component:onlineSetting
				},
				{
					path:'/addShoptype',
					component:addShoptype
				},
				{
					path:'/changeStoretype',
					component:changeStoretype
				},
				{
					path:'/addPartner',
					component:addPartner
                },
				{
					path:'/changeMg',
					component:changeMg
				},
				{
					path:'/addStore',
					component:addStore
				},
				{
					path:'/changeStore',
					component:changeStore
				},
				{
					path:'/changeDiscon',
					component:changeDiscon
				},
				{
					path:'/purchaseHeader',
					component:purchaseHeader
				},
				{
					path:'/addShoptab',
					component:addShoptab
				},
				{
					path:'/userAdministrator',
					component:userAdministrator
				},
				{
					path:'/changeUser',
					component:changeUser
				},
				{
					path:'/cardChongzhi',
					component:cardChongzhi
				},
				{
					path:'/purchaseOrder',
					component:purchaseOrder
				},
				{
					path:'/returnedOrders',
					component:returnedOrders
				},
				{
					path:'/changePassword',
					component:changePassword
				},
				{
					path:'/getCash',
					component:getCash
				},
				{
					path:'/electricitySupplier',
					component:electricitySupplier
				},
				{
					path:'/updataWord',
					component:updataWord
				},
				{
					path:'/keywordJudgement',
					component:keywordJudgement
				},
				{
					path:'/activityContent',
					component:activityContent
				},
				{
					path:'/activityBack',
					component:activityBack
				},
				{
					path:'/addActive',
					component:addActive
				},
				{
					path:'/setingChuangke',
					component:setingChuangke
				},
				{
					path:'/qrcodeList',
					component:qrcodeList
				},
                {
                     path:'/getQcode',
                     component:getQcode
				},
				{
					path:'/getMessage',
					component:getMessage
				},
				{
					path:'/addActiveback',
					component:addActiveback
				},
				{
					path:'/deleteQrcode',
					component:deleteQrcode
				},
				{
					path:'/addDongtai',
					component:addDongtai
				},
				{
					path:'/addAdm',
					component:addAdm
				},
				{
					path:'/changheader',
					component:changheader
				},
				{
					path:'/chongfuOrder',
					component:chongfuOrder
				},
				{
					path: '/leadingIn',
					component:leadingIn
				}
			]
		},
		{
			path: '*',
			redirect: '/portal'
		}
	]
})

export default router
